#!/usr/bin/env python
# -*- coding: utf-8 -*- 
import urllib.request
import datetime
import telepot
import re
from time import sleep      # Importing the time library to provide the delays in program
from telepot.loop import MessageLoop
import picamera


now = datetime.datetime.now()

# Setup where we will get our IP address
url = 'http://checkip.dyndns.org'
#print ("Our chosen IP address service is ", url)
# Open up the url, then read the contents, and take away our IP address
request = urllib.request.urlopen(url).read().decode('utf-8')
# We extract the IP address only
ourIP = re.findall("\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}", request)
#ourIP = str(ourIP)
#print ("Our IP address is: ", ourIP)

#Get the photo
camera=picamera.PiCamera()
camera.capture('./capture.jpg')
camera.close()


def action(msg):
    chat_id = msg['chat']['id'] # Receiving the message from telegram
    command = msg['text']   # Getting text from the message
    print ('Received:')
    print(command)
    # Comparing the incoming message to send a reply according to it
    if command == '/hi':
        bot.sendMessage (chat_id, str("Hi!alkis"))
        
    elif command == '/time':
        bot.sendMessage(chat_id, str("Time: ") + str(now.hour) + str(":") + str(now.minute) + str(":") + str(now.second))
        
    elif command == 'ip':
        bot.sendMessage(chat_id, str("H τρέχουσα IP σου ειναι :") + str(ourIP) )      
        
    elif command == '/filip':
        bot.sendMessage(chat_id, str("ninjago"))
        
    elif command == 'Lego':
        bot.sendMessage(chat_id, str("filip"))
        
    elif command == 'C':
        # Sends a message to the chat
        bot.sendPhoto(chat_id, photo=open('./capture.jpg', 'rb'))    
        
    elif command == '/date':
        bot.sendMessage(chat_id, str("Date: ") + str(now.day) + str("/") + str(now.month) + str("/") + str(now.year))
        
        
#sendAudio() to send an audio file
#sendVideo() to send a video clip
#sendDocument() to send a generic file
      
bot = telepot.Bot('11111111111:xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx')
print (bot.getMe())

MessageLoop(bot, action).run_as_thread()
print ('Listening....')

while 1:
    sleep(10)        
        
        

